#!/usr/bin/env python3

"""
Calculate  white matter hyperintensity (WMH) confluence metric described in [...].

The script expects binary or probabilistic WMH masks as input, e.g. generated by FSL TRUENET or BIANCA. WMH are expected to be organised in a BIDS-like directory
structure:

    input_dir/
        sub-001/
            ses-01/
                *_WMH.nii.gz
        sub-002/
            ...

Results are written to a CSV file containing one row per subject-session.

Author: Tanja Schmidt
License: MIT
"""


from pathlib import Path
import numpy as np
import pandas as pd
import nibabel as nib
import argparse
import logging



def calculate_confluence(image,slice_idx,s):
    """
    Calculate WMH confluence in a single axial slice.

    Parameters
    ----------
    image : ndarray
        Binary or probabilistic WMH image.
    slice_idx : int
        Slice index.
    s : float
        Gaussian kernel width that is used for distance-weighing voxel pair interactions (default: 0.05).

    Returns
    -------
    float
        WMH confluence in the slice.
    """
    slice_data_input = image[:,:,slice_idx]
    slice_data = (slice_data_input > 0).astype(np.int_)
    slice_data = pd.DataFrame(slice_data)
    if slice_data.any(axis=None):
        coord = slice_data.stack().reset_index()
        coord.columns =['x', 'y', 'vox_value']
        coord = coord[coord['vox_value']!=0].reset_index()
        coord_vox_value = coord['vox_value'].to_numpy()
        products = pd.DataFrame(coord_vox_value * coord_vox_value[:,None])
        # Elementwise multiplication yields redundant values (a*b = b*a, a*a) which will be set to 0:
        products[:] = np.tril(products.values, k=-1)
        equ_input = products.stack().reset_index()
        equ_input.columns = ['row', 'col', 'product']
        equ_input = equ_input[equ_input['product']!=0]
        equ_input['i'] = coord.loc[equ_input['row'],'x'].to_numpy()
        equ_input['j'] = coord.loc[equ_input['row'],'y'].to_numpy()
        equ_input['m'] = coord.loc[equ_input['col'],'x'].to_numpy()
        equ_input['n'] = coord.loc[equ_input['col'],'y'].to_numpy()
        equ_input['result'] = equ_input['product'] * np.exp(-s*(abs(equ_input['i']-equ_input['m'])**2 + abs(equ_input['j']-equ_input['n'])**2))
        confluence = equ_input['result'].sum()
        return(confluence)

def calculate_volume(image,slice_idx,voxel_size):
    """
    Calculate WMH volume in a single axial slice.

    Parameters
    ----------
    image : ndarray
        Binary or probabilistic WMH image.
    slice_idx : int
        Slice index.
    voxel_size : float
        Volume of one voxel (mm^3).

    Returns
    -------
    float
        WMH volume in the slice.
    """
    WMH_vox_count = np.count_nonzero(image[:, :, slice_idx])
    WMH_vol = WMH_vox_count * voxel_size
    return WMH_vol



def main():
    parser = argparse.ArgumentParser(
        description='Calculate WMH confluence for all subjects and sessions.'
    )

    # Required arguments
    parser.add_argument(
        '--input_dir',
        type=Path,
        required=True,
        help='Directory containing subject folders. This is expected to be BIDS-organised, i.e. sub*/ses*/*nii.gz'
    )

    parser.add_argument(
        '--output_dir',
        type=Path,
        required=True,
        help='Directory where the output CSV will be written.'
    )

    # Optional arguments
    parser.add_argument(
        '--s',
        type=float,
        default=0.05,
        help='Gaussian kernel width (default: 0.05).'
    )

    parser.add_argument(
        '--wmh_string',
        type=str,
        default='*_WMH.nii.gz',
        help='Filename pattern identifying WMH masks (default: "*_WMH.nii.gz").'
    )

    parser.add_argument(
        '--voxel_size',
        type=float,
        default=1.0,
        help='Voxel volume in mm^3 (default: 1.0).'
    )

    args = parser.parse_args()

    input_dir = args.input_dir
    output_dir = args.output_dir

    s = args.s
    voxel_size = args.voxel_size
    wmh_string = args.wmh_string

    # Load images, run function calculate_confluence while looping through subjects and slices:
    confluence_list_all = []
    volume_list_all = []
    logging.basicConfig(level=logging.INFO)

    for sub in sorted(input_dir.glob('sub-*')):
        sub_id = sub.name.split('sub-')[1]
        for ses in sorted(sub.glob('ses-*')):
            ses_id = ses.name.split('ses-')[1]
            WMH_matches = list(ses.glob(wmh_string))
            if not WMH_matches:
                logging.info(f'No WMH mask found for {sub_id} {ses_id}, skipping.')
                print(f'No WMH mask found for {sub_id} {ses_id}, skipping.')
                continue
            logging.info(f'Processing subject {sub_id}, session {ses_id}')
            print(f'Processing subject {sub_id}, session {ses_id}.')
            WMH_path = WMH_matches[0]
            WMH_img = nib.load(WMH_path).get_fdata()
            confluence_list = [
                calculate_confluence(WMH_img, slice_idx, s)
                for slice_idx in range(WMH_img.shape[2])
            ]
            volume_list = [
                calculate_volume(WMH_img, slice_idx,voxel_size)
                for slice_idx in range(WMH_img.shape[2])
            ]
            col_name = f'{sub_id}_{ses_id}'
            confluence_list_all.append(pd.Series(confluence_list, name=col_name))
            volume_list_all.append(pd.Series(volume_list, name=col_name))

    confluence_df = pd.concat(confluence_list_all, axis=1)
    volume_df = pd.concat(volume_list_all, axis=1)

    # Normalize confluence by slice volume
    conf_norm = confluence_df / volume_df

    # Summaries
    conf_sum = confluence_df.sum()
    vol_sum = volume_df.sum()
    conf_norm_sum = conf_norm.sum()
    slice_count = (confluence_df > 0).sum()

    confluence_final = pd.DataFrame({
        'confluence': conf_sum,
        'volume': vol_sum,
        'confluence_norm': conf_norm_sum,
        'nonzero_slices': slice_count,
    }).reset_index(names='subject_session')

    confluence_final['confluence_scaled'] = (
        confluence_final['confluence_norm']
        / (30.20349728 * confluence_final['nonzero_slices'])
    )

    # Clean-up and save
    confluence_final[['subject', 'session']] = (
        confluence_final['subject_session']
        .str.split('_', n=1, expand=True)
    )
    confluence_final['subject'] = confluence_final['subject'].astype(int)
    confluence_final[['subject', 'session']] = (
        confluence_final['subject_session']
        .str.split('_', n=1, expand=True)
    )

    confluence_final = confluence_final.drop(
        columns=['confluence', 'confluence_norm', 'nonzero_slices','subject_session']
    )
    confluence_final = confluence_final[
        ['subject', 'session', 'volume', 'confluence_scaled']
    ]
    confluence_final.to_csv(output_dir / 'WMH_confluence.csv', index=False)

if __name__ == "__main__":
    main()